title: LASTIG seminars
description: Webpage for the open LASTIG seminars, half-day, every 2-3 months
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
